name: "Terraform CI/CD & Security Scan"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  terraform-audit:
    name: "Static Analysis & Security Audit"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        continue-on-error: true

      - name: "Tokyo: Init & Validate"
        working-directory: TokyoAPPI/env/tokyo
        run: |
          terraform init -backend=false
          terraform validate

      - name: "São Paulo: Init & Validate"
        working-directory: TokyoAPPI/env/saopaulo
        run: |
          terraform init -backend=false
          terraform validate

      - name: "Run Trivy Security Scan (IaC)"
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          hide-progress: false
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'

      - name: Final Path Verification
        run: ls -R TokyoAPPI/env/